# Travis CI Configuration File

# Tell Travis CI we're using PHP
language: php

notifications:
  email: false

services:
    - mysql

php:
  - 7.1

env:
    global:
        - WP_DB_USER=wordpress
        - WP_DB_PASS=wordpress
        - WP_DB_NAME=wp_tests

matrix:
  include:
    - php: 7.1
      env: WP_VERSION=latest WP_MULTISITE=1

# Clones WordPress and configures our testing environment.
before_script:
    - mysql -u root -e "GRANT ALL PRIVILEGES ON ${WP_DB_NAME}.* TO ${WP_DB_USER} IDENTIFIED BY '${WP_DB_PASS}';"
    - mysql -u root -e "CREATE DATABASE ${WP_DB_NAME};"

install:
    - composer install
    - composer show

script:
  - composer test

after_script:
  # Push coverage off to Codecov
  - bash <(curl -s https://codecov.io/bash)
